# Generated by Django 5.1.3 on 2024-11-09 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 9, 15, 16, 40, 103604), verbose_name='date published'),
        ),
    ]
